=begin
#FreeClimb API

#FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

The version of the OpenAPI document: 1.0.0
Contact: support@freeclimb.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Freeclimb::CreateConference
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Freeclimb::CreateConference do
  let(:instance) { Freeclimb::CreateConference.new }

  describe 'test an instance of CreateConference' do
    it 'should create an instance of CreateConference' do
      expect(instance).to be_instance_of(Freeclimb::CreateConference)
    end
  end

  describe 'test attribute "action_url"' do
    it 'should work' do
      
          instance.action_url = "TEST_STRING"
          expect(instance.action_url).to eq("TEST_STRING")  
        
      
    end
  end
  
  

  describe 'test attribute "_alias"' do
    it 'should work' do
      
          instance._alias = false
          expect(instance._alias).to eq(false)        
        
      
    end
  end
  
  

  describe 'test attribute "play_beep"' do
    it 'assigns value ALWAYS' do
      instance.play_beep = Freeclimb::PlayBeep::ALWAYS
      expect(instance.play_beep).to eq(Freeclimb::PlayBeep::ALWAYS)  
    end
    it 'assigns value NEVER' do
      instance.play_beep = Freeclimb::PlayBeep::NEVER
      expect(instance.play_beep).to eq(Freeclimb::PlayBeep::NEVER)  
    end
    it 'assigns value ENTRY_ONLY' do
      instance.play_beep = Freeclimb::PlayBeep::ENTRY_ONLY
      expect(instance.play_beep).to eq(Freeclimb::PlayBeep::ENTRY_ONLY)  
    end
    it 'assigns value EXIT_ONLY' do
      instance.play_beep = Freeclimb::PlayBeep::EXIT_ONLY
      expect(instance.play_beep).to eq(Freeclimb::PlayBeep::EXIT_ONLY)  
    end
  end
  

  describe 'test attribute "record"' do
    it 'should work' do
      
          instance.record = false
          expect(instance.record).to eq(false)        
        
      
    end
  end
  
  

  describe 'test attribute "status_callback_url"' do
    it 'should work' do
      
          instance.status_callback_url = "TEST_STRING"
          expect(instance.status_callback_url).to eq("TEST_STRING")  
        
      
    end
  end
  
  

  describe 'test attribute "wait_url"' do
    it 'should work' do
      
          instance.wait_url = "TEST_STRING"
          expect(instance.wait_url).to eq("TEST_STRING")  
        
      
    end
  end
  
  
end
