=begin
#FreeClimb API

#FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

The version of the OpenAPI document: 1.0.0
Contact: support@freeclimb.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Freeclimb::GetSpeech
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Freeclimb::GetSpeech do
  let(:instance) { Freeclimb::GetSpeech.new }

  describe 'test an instance of GetSpeech' do
    it 'should create an instance of GetSpeech' do
      expect(instance).to be_instance_of(Freeclimb::GetSpeech)
    end
  end

  describe 'test attribute "action_url"' do
    it 'should work' do
      
          instance.action_url = "TEST_STRING"
          expect(instance.action_url).to eq("TEST_STRING")  
        
        
      
    end
  end
  
  

  describe 'test attribute "grammar_type"' do
    it 'assigns value URL' do
      instance.grammar_type = Freeclimb::GrammarType::URL
      expect(instance.grammar_type).to eq(Freeclimb::GrammarType::URL)  
    end
    it 'assigns value BUILT_IN' do
      instance.grammar_type = Freeclimb::GrammarType::BUILT_IN
      expect(instance.grammar_type).to eq(Freeclimb::GrammarType::BUILT_IN)  
    end
  end
  

  describe 'test attribute "grammar_file"' do
    it 'should work' do
      
          instance.grammar_file = "TEST_STRING"
          expect(instance.grammar_file).to eq("TEST_STRING")  
        
        
      
    end
  end
  
  

  describe 'test attribute "grammar_rule"' do
    it 'should work' do
      
          instance.grammar_rule = "TEST_STRING"
          expect(instance.grammar_rule).to eq("TEST_STRING")  
        
        
      
    end
  end
  
  

  describe 'test attribute "play_beep"' do
    it 'should work' do
      
          instance.play_beep = false
          expect(instance.play_beep).to eq(false)        
        
        
      
    end
  end
  
  

  describe 'test attribute "prompts"' do
    it 'should work' do
      
        
          instance.prompts = ["ELEMENT_1", "ELEMENT_2"]
          expect(instance.prompts).to eq(["ELEMENT_1", "ELEMENT_2"]) 
        
      
    end
  end
  
  

  describe 'test attribute "no_input_timeout_ms"' do
    it 'should work' do
      
          instance.no_input_timeout_ms = 1
          expect(instance.no_input_timeout_ms).to eq(1) 
        
        
      
    end
  end
  
  

  describe 'test attribute "recognition_timeout_ms"' do
    it 'should work' do
      
          instance.recognition_timeout_ms = 1
          expect(instance.recognition_timeout_ms).to eq(1) 
        
        
      
    end
  end
  
  

  describe 'test attribute "confidence_threshold"' do
    it 'should work' do
      
          instance.confidence_threshold = 1
          expect(instance.confidence_threshold).to eq(1) 
        
          instance.confidence_threshold = BigDecimal("1.0")
          expect(instance.confidence_threshold).to eq(BigDecimal("1.0")) 
        
        
      
    end
  end
  
  

  describe 'test attribute "sensitivity_level"' do
    it 'should work' do
      
          instance.sensitivity_level = 1
          expect(instance.sensitivity_level).to eq(1) 
        
          instance.sensitivity_level = BigDecimal("1.0")
          expect(instance.sensitivity_level).to eq(BigDecimal("1.0")) 
        
        
      
    end
  end
  
  

  describe 'test attribute "speech_complete_timeout_ms"' do
    it 'should work' do
      
          instance.speech_complete_timeout_ms = 1
          expect(instance.speech_complete_timeout_ms).to eq(1) 
        
        
      
    end
  end
  
  

  describe 'test attribute "speech_incomplete_timeout_ms"' do
    it 'should work' do
      
          instance.speech_incomplete_timeout_ms = 1
          expect(instance.speech_incomplete_timeout_ms).to eq(1) 
        
        
      
    end
  end
  
  

  describe 'test attribute "privacy_mode"' do
    it 'should work' do
      
          instance.privacy_mode = false
          expect(instance.privacy_mode).to eq(false)        
        
        
      
    end
  end
  
  
end
