# #FreeClimb API
#
# FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@freeclimb.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.9.0
#

require "spec_helper"
require "json"
require "date"
include Freeclimb

# Unit tests for Freeclimb::SayStandardVoice
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Freeclimb::SayStandardVoice do
  let(:instance) { Freeclimb::SayStandardVoice.new }

  describe "test an instance of SayStandardVoice" do
    it "should create an instance of SayStandardVoice" do
      expect(instance).to be_instance_of(Freeclimb::SayStandardVoice)
    end
  end

  describe 'test attribute "HERENA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HERENA = "Herena" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HERENA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Herena")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Herena"
      calculatedValue = Freeclimb::SayStandardVoice::HERENA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HELLE"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HELLE = "Helle" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HELLE
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Helle")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Helle"
      calculatedValue = Freeclimb::SayStandardVoice::HELLE
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEDDA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEDDA = "Hedda" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEDDA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hedda")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hedda"
      calculatedValue = Freeclimb::SayStandardVoice::HEDDA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HAYLEY"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HAYLEY = "Hayley" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HAYLEY
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hayley")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hayley"
      calculatedValue = Freeclimb::SayStandardVoice::HAYLEY
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEATHER"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEATHER = "Heather" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEATHER
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Heather")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Heather"
      calculatedValue = Freeclimb::SayStandardVoice::HEATHER
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HAZEL"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HAZEL = "Hazel" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HAZEL
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hazel")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hazel"
      calculatedValue = Freeclimb::SayStandardVoice::HAZEL
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEERA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEERA = "Heera" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEERA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Heera")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Heera"
      calculatedValue = Freeclimb::SayStandardVoice::HEERA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HELEN"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HELEN = "Helen" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HELEN
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Helen")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Helen"
      calculatedValue = Freeclimb::SayStandardVoice::HELEN
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "ZIRA_PRO"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::ZIRA_PRO = "ZiraPro" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::ZIRA_PRO
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("ZiraPro")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "ZiraPro"
      calculatedValue = Freeclimb::SayStandardVoice::ZIRA_PRO
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HELENA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HELENA = "Helena" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HELENA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Helena")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Helena"
      calculatedValue = Freeclimb::SayStandardVoice::HELENA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HILDA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HILDA = "Hilda" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HILDA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hilda")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hilda"
      calculatedValue = Freeclimb::SayStandardVoice::HILDA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEIDI"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEIDI = "Heidi" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEIDI
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Heidi")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Heidi"
      calculatedValue = Freeclimb::SayStandardVoice::HEIDI
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HARMONIE"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HARMONIE = "Harmonie" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HARMONIE
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Harmonie")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Harmonie"
      calculatedValue = Freeclimb::SayStandardVoice::HARMONIE
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HORTENSE"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HORTENSE = "Hortense" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HORTENSE
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hortense")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hortense"
      calculatedValue = Freeclimb::SayStandardVoice::HORTENSE
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "LUCIA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::LUCIA = "Lucia" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::LUCIA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Lucia")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Lucia"
      calculatedValue = Freeclimb::SayStandardVoice::LUCIA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HARKUA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HARKUA = "Harkua" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HARKUA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Harkua")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Harkua"
      calculatedValue = Freeclimb::SayStandardVoice::HARKUA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEAMI"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEAMI = "Heami" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEAMI
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Heami")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Heami"
      calculatedValue = Freeclimb::SayStandardVoice::HEAMI
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HULDA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HULDA = "Hulda" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HULDA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hulda")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hulda"
      calculatedValue = Freeclimb::SayStandardVoice::HULDA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HANNA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HANNA = "Hanna" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HANNA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hanna")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hanna"
      calculatedValue = Freeclimb::SayStandardVoice::HANNA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "PAULINA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::PAULINA = "Paulina" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::PAULINA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Paulina")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Paulina"
      calculatedValue = Freeclimb::SayStandardVoice::PAULINA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HELOSIA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HELOSIA = "Helosia" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HELOSIA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Helosia")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Helosia"
      calculatedValue = Freeclimb::SayStandardVoice::HELOSIA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HELIA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HELIA = "Helia" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HELIA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Helia")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Helia"
      calculatedValue = Freeclimb::SayStandardVoice::HELIA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "ELENA"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::ELENA = "Elena" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::ELENA
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Elena")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Elena"
      calculatedValue = Freeclimb::SayStandardVoice::ELENA
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HEDVIG"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HEDVIG = "Hedvig" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HEDVIG
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("Hedvig")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "Hedvig"
      calculatedValue = Freeclimb::SayStandardVoice::HEDVIG
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HUN_YEE"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HUN_YEE = "HunYee" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HUN_YEE
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("HunYee")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "HunYee"
      calculatedValue = Freeclimb::SayStandardVoice::HUN_YEE
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "HAN_HAN"' do
    it "should work" do
      expect { Freeclimb::SayStandardVoice::HAN_HAN = "HanHan" }.not_to raise_error
    end
    it "should serialize to enum" do
      expectedValue = Freeclimb::SayStandardVoice::HAN_HAN
      calculatedValue = Freeclimb::SayStandardVoice.build_from_hash("HanHan")
      expect(expectedValue).to eq(calculatedValue)
    end
    it "should deserialize to string" do
      expectedValue = "HanHan"
      calculatedValue = Freeclimb::SayStandardVoice::HAN_HAN
      expect(expectedValue).to eq(calculatedValue)
    end
  end
end
