=begin
#FreeClimb API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Freeclimb::StartRecordCall
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StartRecordCall' do
  before do
    # run before each test
    @instance = Freeclimb::StartRecordCall.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StartRecordCall' do
    it 'should create an instance of StartRecordCall' do
      expect(@instance).to be_instance_of(Freeclimb::StartRecordCall)
    end
  end
end
