=begin
#FreeClimb API

#FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.

The version of the OpenAPI document: 1.0.0
Contact: support@freeclimb.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'
include Freeclimb

# Unit tests for Freeclimb::UpdateCallRequestStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Freeclimb::UpdateCallRequestStatus do
  let(:instance) { Freeclimb::UpdateCallRequestStatus.new }

  describe 'test an instance of UpdateCallRequestStatus' do
    it 'should create an instance of UpdateCallRequestStatus' do
      expect(instance).to be_instance_of(Freeclimb::UpdateCallRequestStatus)
    end
  end
  
  describe 'test attribute "CANCELED"' do
    it 'should work' do
      expect { Freeclimb::UpdateCallRequestStatus::CANCELED = "canceled" }.not_to raise_error
    end
    it 'should serialize to enum' do
      expectedValue = Freeclimb::UpdateCallRequestStatus::CANCELED
      calculatedValue = Freeclimb::UpdateCallRequestStatus::build_from_hash("canceled")
      expect(expectedValue).to eq(calculatedValue)
    end
    it 'should deserialize to string' do
      expectedValue = "canceled"
      calculatedValue = Freeclimb::UpdateCallRequestStatus::CANCELED
      expect(expectedValue).to eq(calculatedValue)
    end
  end

  describe 'test attribute "COMPLETED"' do
    it 'should work' do
      expect { Freeclimb::UpdateCallRequestStatus::COMPLETED = "completed" }.not_to raise_error
    end
    it 'should serialize to enum' do
      expectedValue = Freeclimb::UpdateCallRequestStatus::COMPLETED
      calculatedValue = Freeclimb::UpdateCallRequestStatus::build_from_hash("completed")
      expect(expectedValue).to eq(calculatedValue)
    end
    it 'should deserialize to string' do
      expectedValue = "completed"
      calculatedValue = Freeclimb::UpdateCallRequestStatus::COMPLETED
      expect(expectedValue).to eq(calculatedValue)
    end
  end

end
