# #FreeClimb API
#
# FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@freeclimb.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.9.0
#

require "date"
require "time"

module Freeclimb
  class SayStandardVoice
    HERENA = "Herena".freeze
    HELLE = "Helle".freeze
    HEDDA = "Hedda".freeze
    HAYLEY = "Hayley".freeze
    HEATHER = "Heather".freeze
    HAZEL = "Hazel".freeze
    HEERA = "Heera".freeze
    HELEN = "Helen".freeze
    ZIRA_PRO = "ZiraPro".freeze
    HELENA = "Helena".freeze
    HILDA = "Hilda".freeze
    HEIDI = "Heidi".freeze
    HARMONIE = "Harmonie".freeze
    HORTENSE = "Hortense".freeze
    LUCIA = "Lucia".freeze
    HARKUA = "Harkua".freeze
    HEAMI = "Heami".freeze
    HULDA = "Hulda".freeze
    HANNA = "Hanna".freeze
    PAULINA = "Paulina".freeze
    HELOSIA = "Helosia".freeze
    HELIA = "Helia".freeze
    ELENA = "Elena".freeze
    HEDVIG = "Hedvig".freeze
    HUN_YEE = "HunYee".freeze
    HAN_HAN = "HanHan".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = SayStandardVoice.constants.select { |c| SayStandardVoice.const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #SayStandardVoice" if constantValues.empty?
      value
    end
  end
end
